### ISSUE TITLE
Merge xenial branch from master

### ISSUE THREAD

**Issue by Flohack74** [ubports/calculator-app#12]
Our automatic build needs the xenial branch to be able to build nightly versions correctly into the rootfs image.

**Comment by mariogrip** [comment]
Master builds mullti versions, for both xenial and bionic

**Comment by Flohack74** [comment]
Ok but at least we need to make it consisten. I can see lots of different combinations for branches on the core apps. Also we need to remove the stale ones.

**Comment by bhdouglass** [comment]
So which branches should there be? It seems we keep going back and forth on this issue

**Comment by Flohack74** [comment]
Basically we need all 3, to cover all possible situations. As we still dont know if we will ever have release-specific things which would make an app not able to compile from the same branch. Plus I am missing smth to stage core apps for Q&A. Currently this means if you commit to master that the app is compiled and integrated into the image the next night. This might be not what we always want.

**Comment by bhdouglass** [comment]
so, `master`, `xenial`, and `vivid`? Seems like a lot for the calculator app.

**Comment by Flohack74** [comment]
Pure QML apps wont need release branches probably... But we did not finish this discussion ;)

**Comment by bhdouglass** [comment]
Ok, I'll make those branches and we can go from there.
