### ISSUE TITLE
Update math.js or include as package

### ISSUE THREAD

**Issue by Flohack74** [ubports/calculator-app#31]
The included mth.js library is from 2015 - It would be good to find a way to either update it constantly by human interaction, or to pull it in as a package and auto-update it. I do not think that updates will easily break the calculator.

**Comment by AnotherStranger** [comment]
I created a pull request to update math.js to the newest version. #32

**Comment by bhdouglass** [comment]
#32 was merged and I updated it to use npm in this commit: https://github.com/ubports/calculator-app/commit/98e76832d9456f5f73caa287f06e649410740c0b

**Comment by bhdouglass** [comment]
Yep! I'm using the calculator app as a test to move to gitlab's ci, so hopefully it'll get released tonight
